### ISSUE TITLE
Cannot find path 'D:\a\1\a\EntityFramework.6.2.0\tools\migrate.exe' because it does not exist

### ISSUE THREAD

**Issue by dev-msalah** [tobania/VSTS.Extension.EntityFrameworkMigrations#2]
I got the following error 
2019-02-15T15:07:27.8988152Z ##[error]System.Management.Automation.ItemNotFoundException: Cannot find path 'D:\a\1\a\EntityFramework.6.2.0\tools\migrate.exe' because it does not exist.
2019-02-15T15:07:27.8988494Z    at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
2019-02-15T15:07:27.8988597Z    at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
2019-02-15T15:07:27.8988653Z    at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
2019-02-15T15:07:27.8988744Z    at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
2019-02-15T15:07:27.8988798Z    at System.Management.Automation.SessionStateInternal.CopyItem(String[] paths, String copyPath, Boolean recurse, CopyContainers copyContainers, CmdletProviderContext context)
2019-02-15T15:07:27.8988862Z    at Microsoft.PowerShell.Commands.CopyItemCommand.ProcessRecord()

My Configurations are: 
![image](https://user-images.githubusercontent.com/13393514/52865320-48be4400-3134-11e9-8372-6c57bca578b9.png)

**Comment by ygeelen-tb** [comment]
I think your "NuGet packages folder" parameter doesn't contain the correct basepath..

Also, did you include the NuGet package EntityFramework to your project and restored it prior to the Copy EntityFramework migrate.exe task?

**Comment by dev-msalah** [comment]
I fixed this issue. Now i have another issue at release 

[error]Microsoft.PowerShell.Commands.WriteErrorException: EntityFramework.dll was not found in the provided bin folder

**Comment by ygeelen-tb** [comment]
Alright. Could you please include a screenshot of your release task configuration also?

**Comment by dev-msalah** [comment]
Build configuration
![image](https://user-images.githubusercontent.com/13393514/52944625-c4540700-3367-11e9-927b-a63a6c6cd4c6.png)

Release configuration
![image](https://user-images.githubusercontent.com/13393514/52944666-dcc42180-3367-11e9-92b7-ee1fdebaf9f0.png)

Note: I added release task after website deploy

**Comment by ygeelen-tb** [comment]
Please download your build output zip and see if the folder structure matches with your release task configuration.

My first take would be the "Working directory" + "Binaries folder" combination is invalid.
Does EntityFramework.dll exist in ...\KIT.Website\bin\Release ?

**Comment by dev-msalah** [comment]
the output path of my build is "Content\D_C\a\1\s\KIT\KIT.Website\obj\Release\Package\PackageTmp\bin". is that means i have to set the working directory to that path.

**Comment by ygeelen-tb** [comment]
No that doesn't seem right, obj is just a temporary folder.
Can you please download the build artifact (zip file) of your build?
And then search for all directories that contain EntityFramework.dll

**Comment by dev-msalah** [comment]
that was the only path that contains EntityFramework.dll and it doesn't contain migrate.exe

**Comment by ygeelen-tb** [comment]
Of course it's not in the obj subfolder, since you copied migrate.exe to \KIT.Website\Migrate\ folder in the build task. Can you find it there.

Did you include the NuGet package EntityFramework to your KIT.Website project also and restored it?
If it's referenced then you should find the binaries in the bin folder as well.

"Binaries folder" should be "bin" I think
"Target assembly" should be "KIT.Data.dll" I think

**Comment by dev-msalah** [comment]
I can't find Migrate folder in the final build path i think its the wrong path i think 

yes i included Entityframework in the website project and its restored successfully as i can find it under bin.

do  you think that adding copy migrate task in build pipeline after building my solution correct?
Also, should i add the same variables added to copy migrate task "ie: $(build.artifactstagingdirectory)" to Apply entity framework task in release task?

**Comment by ygeelen-tb** [comment]
Perhaps first make sure the build task works before fixing the release task.

migrate.exe doesn't have to be in your bin, as you can configure in the release task where to look it up.

Yes but with web projects it's a bit different as their output is published after building into a subdirectory possibly. Do you have access to the build server?

In release tasks I usually use different variable like System.DefaultWorkingDirectory

**Comment by dev-msalah** [comment]
Ok, so at build pipeline at Copy Migrate.exe. I will copy my path to "$(build.artifactstagingdirectory)\KIT\KIT.Website\Migrate" this should be at the root of website. right?

**Comment by ygeelen-tb** [comment]
Yes. Afterwards please check your build artifact if that's the case.

**Comment by saswati-das** [comment]
@dev-msalah  - how do you add a task on Releases - 
![image](https://user-images.githubusercontent.com/44465109/81952822-d4a47180-95fe-11ea-8dc5-a12f053bc3b7.png) ?
